#!/system/bin/sh

# enable charging light while device is on
chmod 777 /sys/devices/virtual/gpio/gpio168/value
if [ -e /data/data/org.teameos.settings.device/app_eos/charging_light ]; then
    echo 0 > /sys/devices/virtual/gpio/gpio168/value
else
    echo 1 > /sys/devices/virtual/gpio/gpio168/value
fi

